name: Generate Konectas Source
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Generate Konectas Source
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Configure NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Checkout repo
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run generate
      - run: |
          git config user.name ${{secrets.USER_NAME}}
          git config user.email ${{secrets.USER_EMAIL}}
          git add .
          git commit -m ":robot: HTML files generated"
          git push

      - name: Deploy GitHub Pages site

        uses: actions/deploy-pages@v4.0.5
